name: Cross Deploy

on:
  push:
    branches: ['testing-actions']
    # tags:
    #   - turso-php-extension/v*.*.*

permissions:
  contents: write

jobs:
  build-and-upload:
    name: Build and upload
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          # Linux x64
          - build: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            php-versions: '8.3'

          # Macos x64
          - build: x86_64-apple-darwin
            os: macos-latest
            target: x86_64-apple-darwin
            php-versions: '8.3'
          - build: macos-arm64
            os: macos-14-xlarge
            target: macos-arm64
            php-versions: '8.3'

    steps:
      #Debug output + special rustup config for the ubuntu/aarch64 runner
      - name: show step matrix details
        run: |
          env
          set -ex
          uname -a
          echo "os: ${{ matrix.os }}"
          echo "variant: $(arch)"
          pwd
          whoami
